version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/package"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/examples"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/examples/typescript"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/demo"
    schedule:
      interval: "monthly"
